version: "2.0"

services:
  datagram:
    image: virgilbb/datagram-node:amd64
    build:
      context: .
      dockerfile: Dockerfile
    env:
      - DATAGRAM_LICENSE_KEY=${DATAGRAM_LICENSE_KEY}
      - NODE_NAME=${NODE_NAME:-datagram-node}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    expose:
      - port: 3000
        as: 3000
        to:
          - global: true
      - port: 4000
        as: 4000
        to:
          - global: true

profiles:
  compute:
    datagram:
      resources:
        cpu:
          units: 0.2
        memory:
          size: 256Mi
        storage:
          size: 512Mi
  placement:
    akash:
      pricing:
        datagram:
          denom: uakt
          amount: 1000

deployment:
  datagram:
    akash:
      profile: datagram
      count: 1
